# Generated by Django 4.0.1 on 2022-01-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0005_alter_test_patient_alter_testattribute_test'),
        ('patients', '0002_patient_diagnosys_patient_functional_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment', to='patients.patient')),
                ('tests', models.ManyToManyField(to='tests.Test')),
            ],
        ),
    ]
