# Generated by Django 4.0.1 on 2022-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_testattribute_attribute_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattribute',
            name='unit',
            field=models.CharField(default=0.0, max_length=63),
        ),
    ]
