# Generated by Django 4.0.1 on 2022-01-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_diagnosys_patient_functional_state'),
        ('tests', '0004_alter_testattribute_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='testattribute',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='tests.test'),
        ),
    ]
